#!/usr/bin/env bash
# Publish Godogen runtime files into a target game repo.
#
# Usage:
#   ./publish.sh --engine godot|bevy|babylon --agent claude|codex [--mode oneshot|interactive] --out <dir> [--force]
#   ./publish.sh --engine godot|bevy|babylon --agent claude|codex [--mode ...] <dir> [--force]
#
# A published repo carries only docs: the runtime manifest (CLAUDE.md / AGENTS.md) for
# the chosen mode, a per-engine guide (<engine>.md), and the asset-gen skill. The agent
# scaffolds the game itself from the engine guide — no project scaffold is shipped.
#
# --mode selects the delivery regime (default: interactive for babylon, oneshot otherwise):
#   oneshot     unattended build; proof of result is a recorded video
#   interactive live, user-steered build (a live URL, or a project the user runs)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
HELPERS="$REPO_ROOT/scripts"

ENGINE=""
AGENT=""
MODE=""
OUT=""
FORCE=0

usage() {
    sed -n '1,13p' "$0" >&2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --engine) ENGINE="${2:-}"; shift 2 ;;
        --agent)  AGENT="${2:-}";  shift 2 ;;
        --mode)   MODE="${2:-}";   shift 2 ;;
        --out)    OUT="${2:-}";    shift 2 ;;
        --force)  FORCE=1;         shift   ;;
        -h|--help) usage; exit 0 ;;
        -*) echo "error: unknown option $1" >&2; usage; exit 1 ;;
        *)
            if [ -n "$OUT" ]; then
                echo "error: target specified more than once" >&2
                exit 1
            fi
            OUT="$1"
            shift
            ;;
    esac
done

case "$ENGINE" in
    godot)   ENGINE_DISPLAY="Godot";      DEFAULT_MODE="oneshot" ;;
    bevy)    ENGINE_DISPLAY="Bevy";       DEFAULT_MODE="oneshot" ;;
    babylon) ENGINE_DISPLAY="Babylon.js"; DEFAULT_MODE="interactive" ;;
    *) echo "error: --engine must be godot, bevy, or babylon" >&2; usage; exit 1 ;;
esac

MODE="${MODE:-$DEFAULT_MODE}"
case "$MODE" in
    oneshot|interactive) ;;
    *) echo "error: --mode must be oneshot or interactive" >&2; usage; exit 1 ;;
esac

# Root for runtime-loaded generated assets, substituted into the asset docs.
case "$ENGINE" in
    babylon) RUNTIME_ASSET_DIR="src/assets" ;;
    *)       RUNTIME_ASSET_DIR="assets" ;;
esac

case "$AGENT" in
    claude)
        MANIFEST="CLAUDE.md"
        SKILLS_DIR_REL=".claude/skills"
        AGENT_NAME="Claude"
        ASSET_SKILL_COMMAND="/asset-gen"
        ;;
    codex)
        MANIFEST="AGENTS.md"
        SKILLS_DIR_REL=".agents/skills"
        AGENT_NAME="Codex"
        ASSET_SKILL_COMMAND="\$asset-gen"
        ;;
    *) echo "error: --agent must be claude or codex" >&2; usage; exit 1 ;;
esac

ASSET_GEN_SKILL_DIR="$SKILLS_DIR_REL/asset-gen"
ENGINE_GUIDE_FILE="$ENGINE.md"

if [ -z "$OUT" ]; then
    echo "error: --out <target_dir> is required" >&2
    usage
    exit 1
fi

TARGET="$(cd "$OUT" 2>/dev/null && pwd || (mkdir -p "$OUT" && cd "$OUT" && pwd))"

if [ "$FORCE" -eq 1 ] && [ -d "$TARGET" ]; then
    echo "Force: cleaning $TARGET"
    rm -rf "${TARGET:?}"
    mkdir -p "$TARGET"
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "Publishing $ENGINE/$AGENT ($MODE) to: $TARGET"

# --- Skills: only the asset-gen skill ---
mkdir -p "$TMP/skills/asset-gen"
rsync -a --delete --exclude='__pycache__/' "$REPO_ROOT/asset-gen/" "$TMP/skills/asset-gen/"

python3 "$HELPERS/render_dir.py" "$TMP/skills" \
    "AGENT_NAME=$AGENT_NAME" \
    "ASSET_GEN_SKILL_DIR=$ASSET_GEN_SKILL_DIR" \
    "ASSET_SKILL_COMMAND=$ASSET_SKILL_COMMAND" \
    "RUNTIME_ASSET_DIR=$RUNTIME_ASSET_DIR"

if [ "$AGENT" = "codex" ]; then
    python3 "$HELPERS/generate_codex_metadata.py" "$TMP/skills"
fi

mkdir -p "$TARGET/$SKILLS_DIR_REL"
rsync -a --delete "$TMP/skills/" "$TARGET/$SKILLS_DIR_REL/"
echo "Installed asset-gen skill"

# --- Manifest: runtime process preamble + the chosen mode block ---
# MODE_BLOCK is passed first so its inner tokens (e.g. ENGINE_GUIDE_FILE) get
# resolved by the later replacements in the same render pass.
MANIFEST_TMP="$TMP/manifest"
mkdir -p "$MANIFEST_TMP"
cp "$REPO_ROOT/prompts/runtime.md" "$MANIFEST_TMP/$MANIFEST"
python3 "$HELPERS/render_dir.py" "$MANIFEST_TMP" \
    "MODE_BLOCK=$(cat "$REPO_ROOT/prompts/$MODE.md")" \
    "ENGINE_NAME=$ENGINE_DISPLAY" \
    "ENGINE_GUIDE_FILE=$ENGINE_GUIDE_FILE" \
    "ASSET_SKILL_COMMAND=$ASSET_SKILL_COMMAND"
cp "$MANIFEST_TMP/$MANIFEST" "$TARGET/$MANIFEST"
echo "Created $MANIFEST ($MODE)"

# --- Per-engine guide (literal markdown) ---
cp "$REPO_ROOT/engines/$ENGINE.md" "$TARGET/$ENGINE_GUIDE_FILE"
echo "Created $ENGINE_GUIDE_FILE"

# --- .gitignore (published instruction files are regenerated by publish.sh) ---
if [ ! -f "$TARGET/.gitignore" ]; then
    {
        if [ "$AGENT" = "claude" ]; then
            printf '.claude\nCLAUDE.md\n'
        else
            printf '.agents\nAGENTS.md\n.codex\n'
        fi
        printf '%s\n' "$ENGINE_GUIDE_FILE"
        case "$ENGINE" in
            godot)
                printf 'assets\nscreenshots\n.godot\n*.import\nbin/\nobj/\n'
                ;;
            bevy)
                printf '/target\n/screenshots\n'
                ;;
            babylon)
                printf '/node_modules\n/dist\n/screenshots\n'
                ;;
        esac
    } > "$TARGET/.gitignore"
    echo "Created .gitignore"
fi

git -C "$TARGET" init -q 2>/dev/null || true

echo "Done."
